'use client'

import { useState } from 'react'
import jsPDF from 'jspdf'

const translations = {
  EN: {
    badge: 'AI COSMETIC INTELLIGENCE',
    title: 'Understand your cosmetic formula.',
    subtitle: 'Paste an INCI list and receive a clear, clinical-style ingredient analysis for safety, benefits and potential concerns.',
    analyzeTitle: 'Analyze Formula',
    resultTitle: 'Analysis Result',
    placeholder: 'Aqua, Glycerin, Niacinamide...',
    button: 'Analyze Formula',
    loading: 'Analyzing...',
    pdf: 'Download Premium PDF Report',
    empty: 'Your AI analysis will appear here after submitting a formula.',
    formulaScore: 'Formula Score',
    hydration: 'Hydration',
    barrier: 'Barrier Support',
    antiAging: 'Anti-Aging',
    acne: 'Acne Safety',
    irritation: 'Irritation Risk',
    benefits: 'KEY BENEFITS',
    ingredients: 'KEY INGREDIENTS',
    concerns: 'POTENTIAL CONCERNS',
    bestFor: 'BEST FOR',
    conclusion: 'PROFESSIONAL CONCLUSION',
    footer: 'Generated by FORMULENS LAB AI',
  },
  DE: {
    badge: 'KI-KOSMETIKANALYSE',
    title: 'Verstehen Sie Ihre kosmetische Formel.',
    subtitle: 'Fügen Sie eine INCI-Liste ein und erhalten Sie eine klare professionelle Analyse zu Nutzen, Sicherheit und möglichen Risiken.',
    analyzeTitle: 'Formel analysieren',
    resultTitle: 'Analyseergebnis',
    placeholder: 'Aqua, Glycerin, Niacinamide...',
    button: 'Formel analysieren',
    loading: 'Analyse läuft...',
    pdf: 'Premium PDF-Bericht herunterladen',
    empty: 'Ihre KI-Analyse erscheint hier nach dem Absenden der Formel.',
    formulaScore: 'Formelbewertung',
    hydration: 'Feuchtigkeit',
    barrier: 'Barriere-Schutz',
    antiAging: 'Anti-Aging',
    acne: 'Akne-Sicherheit',
    irritation: 'Reizungsrisiko',
    benefits: 'WICHTIGE VORTEILE',
    ingredients: 'WICHTIGE INHALTSSTOFFE',
    concerns: 'MÖGLICHE RISIKEN',
    bestFor: 'GEEIGNET FÜR',
    conclusion: 'PROFESSIONELLES FAZIT',
    footer: 'Erstellt von FORMULENS LAB AI',
  },
  RU: {
    badge: 'ИИ-АНАЛИЗ КОСМЕТИКИ',
    title: 'Поймите свою косметическую формулу.',
    subtitle: 'Вставьте INCI-состав и получите понятный профессиональный анализ пользы, безопасности и возможных рисков.',
    analyzeTitle: 'Анализ формулы',
    resultTitle: 'Результат анализа',
    placeholder: 'Aqua, Glycerin, Niacinamide...',
    button: 'Анализировать формулу',
    loading: 'Анализируем...',
    pdf: 'Скачать premium PDF-отчёт',
    empty: 'Результат ИИ-анализа появится здесь после отправки формулы.',
    formulaScore: 'Оценка формулы',
    hydration: 'Увлажнение',
    barrier: 'Поддержка барьера',
    antiAging: 'Антивозрастной эффект',
    acne: 'Безопасность при акне',
    irritation: 'Риск раздражения',
    benefits: 'КЛЮЧЕВЫЕ ПРЕИМУЩЕСТВА',
    ingredients: 'ВАЖНЫЕ ИНГРЕДИЕНТЫ',
    concerns: 'ВОЗМОЖНЫЕ РИСКИ',
    bestFor: 'ПОДХОДИТ ДЛЯ',
    conclusion: 'ПРОФЕССИОНАЛЬНЫЙ ВЫВОД',
    footer: 'Создано FORMULENS LAB AI',
  },
}

export default function Home() {
  const [language, setLanguage] = useState('EN')
  const [inci, setInci] = useState('')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)

  const t = translations[language]

  async function analyzeFormula() {
    if (!inci.trim()) return
    setLoading(true)

    try {
      const response = await fetch('/api/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ inci, language }),
      })

      const data = await response.json()
      if (data.success) setResult(data.data)
    } catch (error) {
      console.log(error)
    }

    setLoading(false)
  }

  function downloadPDF() {
    if (!result) return

    const doc = new jsPDF()
    const pageWidth = 210
    const pageHeight = 297
    let y = 20

    const dark = [7, 7, 14]
    const purple = [180, 120, 255]
    const pink = [255, 70, 180]
    const blue = [70, 190, 255]
    const white = [255, 255, 255]
    const soft = [210, 210, 220]

    doc.setFillColor(...dark)
    doc.rect(0, 0, pageWidth, pageHeight, 'F')

    doc.setTextColor(...white)
    doc.setFontSize(26)
    doc.text('FORMULENS LAB', 18, y)

    y += 8
    doc.setFontSize(10)
    doc.setTextColor(...purple)
    doc.text(t.badge, 18, y)

    y += 8
    doc.setDrawColor(...pink)
    doc.setLineWidth(0.8)
    doc.line(18, y, 192, y)

    y += 14
    doc.setFontSize(11)
    doc.setTextColor(...soft)
    doc.text(new Date().toLocaleDateString(), 18, y)

    y += 18
    doc.setFontSize(18)
    doc.setTextColor(...white)
    doc.text(t.formulaScore, 18, y)

    y += 18
    doc.setFontSize(42)
    doc.setTextColor(...blue)
    doc.text(`${result.formulaScore}/100`, 18, y)

    y += 14

    const metrics = [
      { label: t.hydration, value: result.hydration },
      { label: t.barrier, value: result.barrierSupport },
      { label: t.antiAging, value: result.antiAging },
      { label: t.acne, value: result.acneSafety },
      { label: t.irritation, value: 100 - result.irritationRisk },
    ]

    function metricBar(label, value) {
      doc.setFontSize(10)
      doc.setTextColor(...white)
      doc.text(`${label}: ${value}`, 18, y)

      doc.setFillColor(35, 35, 45)
      doc.roundedRect(18, y + 4, 170, 4, 2, 2, 'F')

      doc.setFillColor(...pink)
      doc.roundedRect(18, y + 4, Math.min(value, 100) * 1.7, 4, 2, 2, 'F')

      y += 13
    }

    metrics.forEach((m) => metricBar(m.label, m.value))

    function checkPage(space = 35) {
      if (y + space > 280) {
        doc.addPage()
        doc.setFillColor(...dark)
        doc.rect(0, 0, pageWidth, pageHeight, 'F')
        y = 22
      }
    }

    function section(title, items) {
      checkPage(40)
      y += 8

      doc.setFontSize(13)
      doc.setTextColor(...purple)
      doc.text(title, 18, y)

      y += 8
      doc.setFontSize(10)
      doc.setTextColor(...white)

      items?.forEach((item) => {
        checkPage(20)
        const lines = doc.splitTextToSize(`• ${item}`, 170)
        doc.text(lines, 22, y)
        y += lines.length * 5.5 + 4
      })
    }

    section(t.benefits, result.keyBenefits)

    checkPage(45)
    y += 8
    doc.setFontSize(13)
    doc.setTextColor(...purple)
    doc.text(t.ingredients, 18, y)

    y += 8
    doc.setFontSize(10)
    doc.setTextColor(...white)

    result.keyIngredients?.forEach((item) => {
      checkPage(22)
      const text = `• ${item.name}: ${item.description}`
      const lines = doc.splitTextToSize(text, 170)
      doc.text(lines, 22, y)
      y += lines.length * 5.5 + 4
    })

    section(t.concerns, result.potentialConcerns)
    section(t.bestFor, result.bestFor)

    checkPage(45)
    y += 8
    doc.setFontSize(13)
    doc.setTextColor(...purple)
    doc.text(t.conclusion, 18, y)

    y += 8
    doc.setFontSize(10)
    doc.setTextColor(...white)

    const conclusion = doc.splitTextToSize(result.professionalConclusion || '', 170)
    doc.text(conclusion, 18, y)

    doc.setFontSize(9)
    doc.setTextColor(150, 150, 160)
    doc.text(t.footer, 18, 287)

    doc.save('formulens-lab-premium-report.pdf')
  }

  const metrics = result
    ? [
        { label: t.hydration, value: result.hydration },
        { label: t.barrier, value: result.barrierSupport },
        { label: t.antiAging, value: result.antiAging },
        { label: t.acne, value: result.acneSafety },
        { label: t.irritation, value: 100 - result.irritationRisk },
      ]
    : []

  return (
    <main className="page">
      <div className="container">
        <div className="top">
          <div>
            <div className="badge">{t.badge}</div>
            <div className="brand">FORMULENS LAB</div>
            <h1 className="title">{t.title}</h1>
            <p className="subtitle">{t.subtitle}</p>
          </div>

          <div className="languages">
            {['EN', 'DE', 'RU'].map((lang) => (
              <button
                key={lang}
                onClick={() => setLanguage(lang)}
                className={language === lang ? 'lang active' : 'lang'}
              >
                {lang}
              </button>
            ))}
          </div>
        </div>

        <div className="grid">
          <div className="card">
            <div className="sectionTitle">{t.analyzeTitle}</div>

            <textarea
              value={inci}
              onChange={(e) => setInci(e.target.value)}
              placeholder={t.placeholder}
              className="textarea"
            />

            <button onClick={analyzeFormula} className="button">
              {loading ? t.loading : t.button}
            </button>

            {result && (
              <button onClick={downloadPDF} className="pdfButton">
                {t.pdf}
              </button>
            )}
          </div>

          <div className="card">
            <div className="sectionTitle">{t.resultTitle}</div>

            {!result ? (
              <div className="empty">{t.empty}</div>
            ) : (
              <>
                <div className="scoreCard">
                  <div className="scoreCircle">{result.formulaScore}</div>
                  <div>
                    <div className="scoreTitle">{t.formulaScore}</div>
                    <div className="scoreText">{result.formulaScore}/100</div>
                  </div>
                </div>

                <div className="metrics">
                  {metrics.map((metric) => (
                    <div key={metric.label} className="metricCard">
                      <div className="metricTop">
                        <span>{metric.label}</span>
                        <span>{metric.value}</span>
                      </div>
                      <div className="progressBg">
                        <div className="progress" style={{ width: `${metric.value}%` }} />
                      </div>
                    </div>
                  ))}
                </div>

                <Block title={t.benefits} items={result.keyBenefits} />
                <IngredientBlock title={t.ingredients} items={result.keyIngredients} />
                <Block title={t.concerns} items={result.potentialConcerns} />
                <Block title={t.bestFor} items={result.bestFor} />

                <div className="section">
                  <div className="sectionHeading">{t.conclusion}</div>
                  <div className="text">{result.professionalConclusion}</div>
                </div>
              </>
            )}
          </div>
        </div>
      </div>

      <style jsx>{`
        .page {
          min-height: 100vh;
          background: #000;
          color: #fff;
          padding: 72px 40px;
          font-family: Inter, Arial, sans-serif;
          background-image: radial-gradient(circle at top left, rgba(120, 0, 255, 0.35), transparent 42%);
        }

        .container {
          max-width: 1400px;
          margin: 0 auto;
        }

        .top {
          display: flex;
          justify-content: space-between;
          gap: 40px;
          align-items: flex-start;
          margin-bottom: 60px;
        }

        .badge {
          font-size: 14px;
          letter-spacing: 3px;
          color: #b46cff;
          margin-bottom: 18px;
          font-weight: 700;
        }

        .brand {
          font-size: 48px;
          font-weight: 900;
          margin-bottom: 28px;
        }

        .title {
          font-size: clamp(48px, 7vw, 92px);
          line-height: 0.95;
          font-weight: 900;
          max-width: 820px;
          margin: 0 0 30px;
        }

        .subtitle {
          font-size: 20px;
          line-height: 1.7;
          color: #d0d0d0;
          max-width: 760px;
          margin: 0;
        }

        .languages {
          display: flex;
          gap: 12px;
          flex-shrink: 0;
        }

        .lang {
          padding: 10px 16px;
          border-radius: 12px;
          border: 1px solid rgba(255, 255, 255, 0.12);
          background: transparent;
          color: #fff;
          cursor: pointer;
          font-weight: 800;
        }

        .lang.active {
          border: 1px solid transparent;
          background: linear-gradient(90deg, #7c3aed, #ff00aa);
        }

        .grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 30px;
          align-items: start;
        }

        .card {
          background: rgba(10, 10, 18, 0.92);
          border: 1px solid rgba(255, 255, 255, 0.06);
          border-radius: 30px;
          padding: 30px;
          box-shadow: 0 30px 100px rgba(0, 0, 0, 0.35);
        }

        .sectionTitle {
          font-size: 24px;
          font-weight: 900;
          margin-bottom: 25px;
        }

        .textarea {
          width: 100%;
          height: 240px;
          background: #000;
          color: #fff;
          border: 1px solid rgba(255, 255, 255, 0.08);
          border-radius: 20px;
          padding: 20px;
          font-size: 18px;
          resize: none;
          outline: none;
          box-sizing: border-box;
        }

        .button,
        .pdfButton {
          width: 100%;
          margin-top: 25px;
          padding: 22px;
          border-radius: 18px;
          border: none;
          color: #fff;
          font-weight: 900;
          font-size: 18px;
          cursor: pointer;
        }

        .button {
          background: linear-gradient(90deg, #7c3aed, #ff00aa);
        }

        .pdfButton {
          margin-top: 14px;
          background: rgba(255, 255, 255, 0.04);
          border: 1px solid rgba(255, 255, 255, 0.12);
          font-size: 16px;
        }

        .empty {
          opacity: 0.65;
          line-height: 1.8;
        }

        .scoreCard {
          display: flex;
          align-items: center;
          gap: 25px;
          margin-bottom: 25px;
        }

        .scoreCircle {
          width: 90px;
          height: 90px;
          border-radius: 50%;
          background: linear-gradient(135deg, #7c3aed, #40c9ff);
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 42px;
          font-weight: 900;
          flex-shrink: 0;
        }

        .scoreTitle {
          color: #d48cff;
          font-weight: 900;
          font-size: 26px;
          margin-bottom: 8px;
        }

        .scoreText {
          font-size: 20px;
        }

        .metrics {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 16px;
          margin-bottom: 25px;
        }

        .metricCard {
          background: rgba(255, 255, 255, 0.03);
          border-radius: 20px;
          padding: 18px;
        }

        .metricTop {
          display: flex;
          justify-content: space-between;
          margin-bottom: 12px;
          font-weight: 800;
          gap: 10px;
        }

        .progressBg {
          width: 100%;
          height: 10px;
          border-radius: 20px;
          background: rgba(255, 255, 255, 0.06);
          overflow: hidden;
        }

        .progress {
          height: 10px;
          border-radius: 20px;
          background: linear-gradient(90deg, #7c3aed, #ff00aa);
        }

        .section {
          background: rgba(255, 255, 255, 0.02);
          border-radius: 24px;
          padding: 24px;
          margin-top: 20px;
        }

        .sectionHeading {
          color: #d48cff;
          letter-spacing: 2px;
          font-weight: 900;
          margin-bottom: 20px;
          font-size: 15px;
        }

        .list {
          display: flex;
          flex-direction: column;
          gap: 14px;
          color: #f0f0f0;
          line-height: 1.7;
        }

        .text {
          line-height: 1.8;
          color: #f0f0f0;
        }

        @media (max-width: 900px) {
          .page {
            padding: 28px 18px 42px;
          }

          .top {
            flex-direction: column;
            gap: 28px;
            margin-bottom: 42px;
          }

          .languages {
            width: 100%;
            display: grid;
            grid-template-columns: repeat(3, 1fr);
          }

          .lang {
            width: 100%;
            padding: 12px 0;
          }

          .brand {
            font-size: 34px;
            margin-bottom: 24px;
          }

          .badge {
            font-size: 12px;
            letter-spacing: 2px;
          }

          .title {
            font-size: 48px;
          }

          .subtitle {
            font-size: 17px;
          }

          .grid {
            grid-template-columns: 1fr;
            gap: 22px;
          }

          .card {
            padding: 22px;
            border-radius: 24px;
          }

          .textarea {
            height: 220px;
            font-size: 16px;
          }

          .metrics {
            grid-template-columns: 1fr;
          }

          .scoreCircle {
            width: 78px;
            height: 78px;
            font-size: 34px;
          }

          .scoreTitle {
            font-size: 22px;
          }
        }
      `}</style>
    </main>
  )
}

function Block({ title, items }) {
  return (
    <div className="section">
      <div className="sectionHeading">{title}</div>
      <div className="list">
        {items?.map((item, index) => (
          <div key={index}>— {item}</div>
        ))}
      </div>
    </div>
  )
}

function IngredientBlock({ title, items }) {
  return (
    <div className="section">
      <div className="sectionHeading">{title}</div>
      <div className="list">
        {items?.map((item, index) => (
          <div key={index}>
            <strong>{item.name}</strong>: {item.description}
          </div>
        ))}
      </div>
    </div>
  )
}
