export const products = {
  // =========================
  // BALANCE
  // =========================

  balance_cleansing_mousse: {
    ref: '10105',
    name: 'BALANCE Cleansing Mousse',
    line: 'BALANCE',
    category: 'cleanser',
    step: 'Reinigung',
    phase: 'cleansing',
    professional: true,
    homecare: true,
    goals: ['acne', 'oil_control', 'purifying'],
    concerns: ['acne', 'oily_skin', 'comedones', 'blackheads', 'excess_sebum'],
    skinTypes: ['oily', 'combination', 'acne_prone'],
    purpose: 'Tägliche Reinigung bei fettiger, unreiner und zu Akne neigender Haut.',
  },

  balance_balancing_lotion: {
    ref: '10107',
    name: 'BALANCE Balancing Lotion',
    line: 'BALANCE',
    category: 'toner',
    step: 'Tonisierung',
    phase: 'toning',
    professional: false,
    homecare: true,
    goals: ['acne', 'oil_control', 'renewal'],
    concerns: ['oily_skin', 'acne', 'enlarged_pores', 'excess_sebum'],
    skinTypes: ['oily', 'combination', 'acne_prone'],
    purpose: 'Balanciert die Haut, reguliert Talgproduktion und unterstützt ein klareres Hautbild.',
  },

  balance_pure_regulator: {
    ref: '10135',
    name: 'BALANCE Pure Regulator Serum Gel',
    line: 'BALANCE',
    category: 'serum',
    step: 'Serum',
    phase: 'active',
    professional: true,
    homecare: false,
    goals: ['acne', 'oil_control', 'purifying'],
    concerns: ['acne', 'oily_skin', 'impurities', 'enlarged_pores'],
    skinTypes: ['oily', 'combination', 'acne_prone'],
    purpose: 'Seboregulierendes Serum-Gel bei fettiger Haut, Unreinheiten und vergrößerten Poren.',
  },

  balance_hydro_balance: {
    ref: '10131',
    name: 'BALANCE Hydro Balance Gel-Cream',
    line: 'BALANCE',
    category: 'cream',
    step: 'Pflege',
    phase: 'final',
    professional: false,
    homecare: true,
    goals: ['hydration', 'oil_control', 'balancing'],
    concerns: ['oily_skin', 'dehydration', 'excess_sebum'],
    skinTypes: ['oily', 'combination', 'young_skin'],
    purpose: 'Leichte Feuchtigkeitspflege für fettige und Mischhaut.',
  },

  balance_drying_gel: {
    ref: '10112',
    name: 'BALANCE Drying Gel',
    line: 'BALANCE',
    category: 'spot_care',
    step: 'SOS',
    phase: 'local_correction',
    professional: true,
    homecare: true,
    goals: ['acne', 'local_correction', 'purifying'],
    concerns: ['pimples', 'active_acne', 'post_acne_marks', 'inflammation'],
    skinTypes: ['oily', 'combination', 'acne_prone'],
    purpose: 'Lokale Pflege bei einzelnen Unreinheiten und Pickeln.',
  },

  // =========================
  // NICELY
  // =========================

  nicely_gentle_cleanser: {
    ref: '10701',
    name: 'NICELY Gentle Cleanser',
    line: 'NICELY',
    category: 'cleanser',
    step: 'Reinigung',
    phase: 'cleansing',
    professional: true,
    homecare: true,
    goals: ['sensitive', 'barrier_repair', 'hydration'],
    concerns: ['redness', 'reactivity', 'tightness', 'dehydration'],
    skinTypes: ['sensitive', 'dry', 'reactive', 'all'],
    purpose: 'Sanfte Reinigung für empfindliche, reaktive und gerötete Haut.',
  },

  nicely_sweet_toner: {
    ref: '10703',
    name: 'NICELY Sweet Toner',
    line: 'NICELY',
    category: 'toner',
    step: 'Tonisierung',
    phase: 'toning',
    professional: true,
    homecare: true,
    goals: ['hydration', 'barrier_repair', 'sensitive'],
    concerns: ['redness', 'tightness', 'dehydration', 'reactivity'],
    skinTypes: ['sensitive', 'dry', 'reactive', 'all'],
    purpose: 'Beruhigendes Gesichtswasser zur Unterstützung der Hautbarriere.',
  },

  nicely_hydration_serum: {
    ref: '10710',
    name: 'NICELY Skincare Hydration Serum',
    line: 'NICELY',
    category: 'serum',
    step: 'Serum',
    phase: 'active',
    professional: false,
    homecare: true,
    goals: ['hydration', 'barrier_repair', 'sensitive'],
    concerns: ['dehydration', 'redness', 'wrinkles_from_dehydration'],
    skinTypes: ['sensitive', 'dry', 'reactive', 'all'],
    purpose: 'Feuchtigkeit und Barriereunterstützung bei empfindlicher Haut.',
  },

  nicely_hydration_cream: {
    ref: '10711',
    name: 'NICELY Skincare Hydration Cream',
    line: 'NICELY',
    category: 'cream',
    step: 'Pflege',
    phase: 'final',
    professional: false,
    homecare: true,
    goals: ['hydration', 'barrier_repair', 'sensitive', 'repair'],
    concerns: ['redness', 'tightness', 'dehydration', 'reactivity'],
    skinTypes: ['sensitive', 'dry', 'reactive', 'all'],
    purpose: 'Beruhigende Feuchtigkeitspflege zur Stärkung der Hautschutzbarriere.',
  },

  nicely_nutrition_cream: {
    ref: '10713',
    name: 'NICELY Skincare Nutrition Cream',
    line: 'NICELY',
    category: 'cream',
    step: 'Pflege',
    phase: 'final',
    professional: false,
    homecare: true,
    goals: ['nutrition', 'barrier_repair', 'comfort'],
    concerns: ['dryness', 'lipid_deficiency', 'tightness', 'reactivity'],
    skinTypes: ['dry', 'sensitive', 'reactive'],
    purpose: 'Nährende Pflege zur Unterstützung des Hydrolipidfilms und der Hautbarriere.',
  },

  nicely_smooth_final_spf50: {
    ref: '10709',
    name: 'NICELY Smooth Final Cream',
    line: 'NICELY',
    category: 'spf',
    step: 'Schutz',
    phase: 'protection',
    professional: true,
    homecare: true,
    goals: ['sun_protection', 'barrier_repair', 'sensitive'],
    concerns: ['redness', 'sensitivity', 'photoaging'],
    skinTypes: ['sensitive', 'reactive', 'all'],
    purpose: 'Täglicher Schutz für empfindliche Haut.',
  },

  // =========================
  // GLACIAR
  // =========================

  glaciar_cleansing_milk: {
    ref: '10102',
    name: 'GLACIAR Cleansing Milk',
    line: 'GLACIAR',
    category: 'cleanser',
    step: 'Reinigung',
    phase: 'cleansing',
    professional: false,
    homecare: true,
    goals: ['hydration', 'barrier_repair', 'comfort'],
    concerns: ['dehydration', 'dryness', 'tightness', 'sensitivity'],
    skinTypes: ['dry', 'normal', 'sensitive'],
    purpose: 'Sanfte Reinigung für trockene, normale und feuchtigkeitsarme Haut.',
  },

  glaciar_soft_lotion: {
    ref: '10104',
    name: 'GLACIAR Soft Lotion',
    line: 'GLACIAR',
    category: 'toner',
    step: 'Tonisierung',
    phase: 'toning',
    professional: false,
    homecare: true,
    goals: ['hydration', 'barrier_repair', 'comfort'],
    concerns: ['dehydration', 'dryness', 'tightness'],
    skinTypes: ['dry', 'normal', 'combination', 'sensitive'],
    purpose: 'Feuchtigkeitsspendende Lotion für ein frisches und komfortables Hautgefühl.',
  },

  hydraluronic_serum_gel: {
    ref: '10126',
    name: 'Hydraluronic Serum Gel',
    line: 'GLACIAR',
    category: 'serum',
    step: 'Serum',
    phase: 'active',
    professional: true,
    homecare: false,
    goals: ['hydration', 'anti_age', 'redensifying', 'firming'],
    concerns: ['dehydration', 'wrinkles', 'loss_of_elasticity'],
    skinTypes: ['dry', 'normal', 'sensitive', 'all'],
    purpose: 'Intensive Feuchtigkeit mit Hyaluronsäure für feuchtigkeitsarme Haut.',
  },

  glaciar_hydration_cream: {
    ref: '10121',
    name: 'GLACIAR Hydration Gel-Cream',
    line: 'GLACIAR',
    category: 'cream',
    step: 'Pflege',
    phase: 'final',
    professional: false,
    homecare: true,
    goals: ['hydration', 'barrier_repair', 'comfort'],
    concerns: ['dehydration', 'tightness'],
    skinTypes: ['normal', 'combination'],
    purpose: 'Feuchtigkeitspflege für normale und Mischhaut.',
  },

  glaciar_plus_hydration_cream: {
    ref: '10124',
    name: 'GLACIAR + Hydration Cream',
    line: 'GLACIAR',
    category: 'cream',
    step: 'Pflege',
    phase: 'final',
    professional: false,
    homecare: true,
    goals: ['hydration', 'nutrition', 'barrier_repair', 'comfort'],
    concerns: ['dryness', 'dehydration', 'tightness', 'sensitivity'],
    skinTypes: ['dry', 'very_dry', 'sensitive'],
    purpose: 'Reichhaltigere Feuchtigkeitspflege für trockene Haut.',
  },

  hydro_repairer_serum: {
    ref: '10123',
    name: 'Hydro-Repairer Serum',
    line: 'GLACIAR',
    category: 'serum',
    step: 'Serum',
    phase: 'active',
    professional: false,
    homecare: true,
    goals: ['hydration', 'repair', 'regeneration', 'barrier_repair'],
    concerns: ['dehydration', 'wrinkles_from_dehydration', 'tightness'],
    skinTypes: ['dry', 'normal', 'sensitive', 'all'],
    purpose: 'Reparierendes Feuchtigkeitsserum bei starkem Feuchtigkeitsmangel.',
  },

  glaciar_mask: {
    ref: '10110',
    name: 'GLACIAR Mask',
    line: 'GLACIAR',
    category: 'mask',
    step: 'Maske',
    phase: 'mask',
    professional: true,
    homecare: false,
    goals: ['hydration', 'soothing', 'repair', 'post_procedure'],
    concerns: ['dehydration', 'redness', 'sensitivity'],
    skinTypes: ['dry', 'normal', 'sensitive', 'all'],
    purpose: 'Beruhigende und reparierende Maske für Feuchtigkeit, Komfort und Regeneration.',
  },

  // =========================
  // BECLARITY
  // =========================

  beclarity_clarifying_cleanser: {
    ref: '10270',
    name: 'BECLARITY Clarifying Cleanser',
    line: 'BECLARITY',
    category: 'cleanser',
    step: 'Reinigung',
    phase: 'cleansing',
    professional: true,
    homecare: true,
    goals: ['pigmentation', 'brightening', 'even_tone'],
    concerns: ['pigmentation', 'dark_spots', 'uneven_tone', 'post_acne_marks'],
    skinTypes: ['all'],
    purpose: 'Reinigung bei Pigmentflecken, unebenem Teint und postinflammatorischen Flecken.',
  },

  beclarity_dark_spot_eraser: {
    ref: '10271',
    name: 'BECLARITY Dark Spot Eraser',
    line: 'BECLARITY',
    category: 'spot_care',
    step: 'Serum',
    phase: 'local_correction',
    professional: false,
    homecare: true,
    goals: ['pigmentation', 'spot_correction', 'brightening'],
    concerns: ['dark_spots', 'melasma', 'localized_pigmentation'],
    skinTypes: ['all'],
    purpose: 'Gezielte Pflege bei dunklen Flecken und Hyperpigmentierung.',
  },

  beclarity_blemish_corrector_serum: {
    ref: '10272',
    name: 'BECLARITY Blemish Corrector Serum',
    line: 'BECLARITY',
    category: 'serum',
    step: 'Serum',
    phase: 'active',
    professional: false,
    homecare: true,
    goals: ['pigmentation', 'brightening', 'antioxidant', 'even_tone'],
    concerns: ['pigmentation', 'dark_spots', 'uneven_tone', 'photoaging'],
    skinTypes: ['all'],
    purpose: 'Ausgleichendes Serum bei unebenem Teint und Pigmentverschiebungen.',
  },

  beclarity_blemish_controller_spf50: {
    ref: '10274',
    name: 'BECLARITY Blemish Controller Cream SPF50',
    line: 'BECLARITY',
    category: 'spf',
    step: 'Schutz',
    phase: 'protection',
    professional: false,
    homecare: true,
    goals: ['pigmentation', 'sun_protection', 'anti_photoaging'],
    concerns: ['pigmentation', 'dark_spots', 'photoaging'],
    skinTypes: ['normal', 'dry', 'mature'],
    purpose: 'Tägliche Pflege mit SPF50 bei Pigmentflecken und unebenem Teint.',
  },

  // =========================
  // CELL
  // =========================

  cell_activator_serum: {
    ref: '10143',
    name: 'CELL Activator Nourishing Anti-Ageing Serum',
    line: 'CELL',
    category: 'serum',
    step: 'Serum',
    phase: 'active',
    professional: false,
    homecare: true,
    goals: ['anti_age', 'regeneration', 'nutrition', 'antioxidant'],
    concerns: ['wrinkles', 'dullness', 'loss_of_vitality', 'dryness'],
    skinTypes: ['normal', 'dry', 'mature', 'all'],
    purpose: 'Nährendes Anti-Aging-Serum bei ersten Alterszeichen und Vitalitätsverlust.',
  },

  cell_vitality_cream: {
    ref: '10141',
    name: 'CELL Vitality Revitalising Anti-Ageing Cream',
    line: 'CELL',
    category: 'cream',
    step: 'Pflege',
    phase: 'final',
    professional: false,
    homecare: true,
    goals: ['anti_age', 'regeneration', 'nutrition', 'firming'],
    concerns: ['wrinkles', 'loss_of_elasticity', 'dryness'],
    skinTypes: ['normal', 'dry', 'mature'],
    purpose: 'Revitalisierende Anti-Aging-Pflege zur Unterstützung der Hautelastizität.',
  },

  cell_eye_cream: {
    ref: '10144',
    name: 'CELL Eyes Anti-Ageing Eye Contour',
    line: 'CELL',
    category: 'eye_care',
    step: 'Augenpflege',
    phase: 'eye_care',
    professional: false,
    homecare: true,
    goals: ['anti_age', 'draining', 'decongesting'],
    concerns: ['eye_bags', 'dark_circles', 'fine_lines'],
    skinTypes: ['all'],
    purpose: 'Pflege für die Augenpartie bei ersten Linien, Trockenheit und Vitalitätsverlust.',
  },

  // =========================
  // CELL C
  // =========================

  cell_c_cleansing_mousse: {
    ref: '10175',
    name: 'CELL C Cleansing Mousse',
    line: 'CELL C',
    category: 'cleanser',
    step: 'Reinigung',
    phase: 'cleansing',
    professional: true,
    homecare: true,
    goals: ['glow', 'antioxidant', 'hydration'],
    concerns: ['dullness', 'uneven_tone', 'oxidative_stress'],
    skinTypes: ['normal', 'combination'],
    purpose: 'Reinigung mit Vitamin-C-Konzept für Glow und Frische.',
  },

  cell_c_renewal_serum: {
    ref: '10173',
    name: 'CELL C Renewal Serum',
    line: 'CELL C',
    category: 'serum',
    step: 'Serum',
    phase: 'active',
    professional: false,
    homecare: true,
    goals: ['glow', 'renewal', 'pigmentation', 'anti_age'],
    concerns: ['dullness', 'pigmentation', 'uneven_tone', 'first_wrinkles'],
    skinTypes: ['normal', 'combination', 'mature'],
    purpose: 'AHA- und Vitamin-C-Serum für Glow, Hauterneuerung und ebenmäßigeren Teint.',
  },

  cell_c_regenerating_cream: {
    ref: '10171',
    name: 'CELL C Antiage Cellular Regenerating Cream',
    line: 'CELL C',
    category: 'cream',
    step: 'Pflege',
    phase: 'final',
    professional: false,
    homecare: true,
    goals: ['glow', 'anti_age', 'antioxidant', 'regeneration'],
    concerns: ['dullness', 'first_wrinkles', 'uneven_tone'],
    skinTypes: ['normal', 'combination'],
    purpose: 'Vitamin-C-Anti-Aging-Pflege für normale und Mischhaut.',
  },

  cell_c_hydro_nourishing_cream: {
    ref: '10172',
    name: 'CELL C Antiage Hydro-Nourishing Cream',
    line: 'CELL C',
    category: 'cream',
    step: 'Pflege',
    phase: 'final',
    professional: true,
    homecare: false,
    goals: ['glow', 'anti_age', 'nutrition', 'hydration'],
    concerns: ['dullness', 'dryness', 'photoaging'],
    skinTypes: ['normal', 'dry', 'mature'],
    purpose: 'Reichhaltigere Vitamin-C-Pflege für trockenere Haut.',
  },

  cell_c_hydro_c_cream: {
    ref: '10170',
    name: 'CELL C Hydro C Cream',
    line: 'CELL C',
    category: 'cream',
    step: 'Pflege',
    phase: 'final',
    professional: false,
    homecare: true,
    goals: ['glow', 'hydration', 'antioxidant', 'prevention'],
    concerns: ['dullness', 'first_wrinkles', 'dehydration'],
    skinTypes: ['normal', 'combination', 'young_skin'],
    purpose: 'Leichtere antioxidative Feuchtigkeitspflege für Glow, Prävention und junge Haut.',
  },

  cell_c_light_lifting_serum_gel: {
    ref: '10145',
    name: 'CELL C Light & Lifting Serum Gel',
    line: 'CELL C',
    category: 'serum',
    step: 'Serum',
    phase: 'active',
    professional: true,
    homecare: false,
    goals: ['glow', 'lifting', 'firming', 'brightening'],
    concerns: ['dullness', 'expression_lines', 'uneven_tone', 'loss_of_firmness'],
    skinTypes: ['normal', 'combination', 'mature'],
    purpose: 'Vitamin-C-Serum-Gel für sofortigen Glow, Frische und Lifting-Effekt.',
  },

  // =========================
  // MYCODE ADVANCED HOMECARE
  // =========================

  mycode_011: {
    ref: '10611',
    name: 'MYCODE Glowing Revitalising Facial Serum',
    line: 'MYCODE ADVANCED',
    category: 'serum',
    step: 'Serum',
    phase: 'active',
    professional: false,
    homecare: true,
    goals: ['glow', 'anti_age', 'antioxidant', 'regeneration'],
    concerns: ['dullness', 'fatigue', 'oxidative_stress'],
    skinTypes: ['all', 'mature'],
    purpose: 'Revitalisierendes Serum für müde, fahle Haut, Glow und antioxidative Unterstützung.',
  },

  mycode_021: {
    ref: '10621',
    name: 'MYCODE Calming Decongesting Facial Serum',
    line: 'MYCODE ADVANCED',
    category: 'serum',
    step: 'Serum',
    phase: 'active',
    professional: false,
    homecare: true,
    goals: ['sensitive', 'soothing', 'regeneration', 'anti_age'],
    concerns: ['redness', 'reactivity', 'irritation'],
    skinTypes: ['sensitive', 'reactive', 'mature'],
    purpose: 'Beruhigendes Serum bei empfindlicher, reaktiver Haut, Rötungen und Irritationen.',
  },

  mycode_022: {
    ref: '10622',
    name: 'MYCODE Calming Comforting Face Cream',
    line: 'MYCODE ADVANCED',
    category: 'cream',
    step: 'Pflege',
    phase: 'final',
    professional: false,
    homecare: true,
    goals: ['sensitive', 'comfort', 'barrier_repair', 'anti_age'],
    concerns: ['redness', 'tightness', 'irritation'],
    skinTypes: ['sensitive', 'reactive', 'mature'],
    purpose: 'Beruhigende Komfortcreme zur Unterstützung empfindlicher und irritierter Haut.',
  },

  mycode_051: {
    ref: '10651',
    name: 'MYCODE Plumping Replenish Facial Serum',
    line: 'MYCODE ADVANCED',
    category: 'serum',
    step: 'Serum',
    phase: 'active',
    professional: false,
    homecare: true,
    goals: ['anti_age', 'plumping', 'redensifying', 'hydration'],
    concerns: ['wrinkles', 'volume_loss', 'dehydration'],
    skinTypes: ['mature', 'dry', 'normal'],
    purpose: 'Aufpolsterndes Serum bei Falten, Volumenverlust und sichtbaren Alterszeichen.',
  },

  mycode_052: {
    ref: '10652',
    name: 'MYCODE Plumping Redensifying Face Cream',
    line: 'MYCODE ADVANCED',
    category: 'cream',
    step: 'Pflege',
    phase: 'final',
    professional: false,
    homecare: true,
    goals: ['anti_age', 'plumping', 'firming', 'hydration'],
    concerns: ['wrinkles', 'volume_loss', 'loss_of_density'],
    skinTypes: ['mature', 'normal', 'dry'],
    purpose: 'Redensifizierende Anti-Aging-Creme bei Falten und nachlassender Hautdichte.',
  },

  mycode_053: {
    ref: '10653',
    name: 'MYCODE Plumping Ultra Rich Redensifying Face Cream',
    line: 'MYCODE ADVANCED',
    category: 'cream',
    step: 'Pflege',
    phase: 'final',
    professional: false,
    homecare: true,
    goals: ['anti_age', 'plumping', 'nutrition', 'hydration'],
    concerns: ['wrinkles', 'dryness', 'volume_loss'],
    skinTypes: ['mature', 'dry', 'very_dry'],
    purpose: 'Reichhaltige redensifizierende Creme für sehr trockene, reife Haut mit Falten.',
  },

  mycode_061: {
    ref: '10661',
    name: 'MYCODE Firming Restructuring Facial Serum',
    line: 'MYCODE ADVANCED',
    category: 'serum',
    step: 'Serum',
    phase: 'active',
    professional: false,
    homecare: true,
    goals: ['lifting', 'firming', 'anti_age', 'regeneration'],
    concerns: ['flaccidity', 'loss_of_firmness', 'loss_of_contours'],
    skinTypes: ['mature', 'normal', 'dry'],
    purpose: 'Straffendes Serum bei Elastizitätsverlust, Konturverlust und nachlassender Festigkeit.',
  },

  mycode_062: {
    ref: '10662',
    name: 'MYCODE Firming Reaffirming Face Cream',
    line: 'MYCODE ADVANCED',
    category: 'cream',
    step: 'Pflege',
    phase: 'final',
    professional: false,
    homecare: true,
    goals: ['lifting', 'firming', 'anti_age', 'plumping'],
    concerns: ['flaccidity', 'loss_of_firmness', 'loss_of_contours'],
    skinTypes: ['mature', 'normal', 'dry'],
    purpose: 'Festigende Creme zur Unterstützung der Hautkonturen und Straffheit.',
  },

  mycode_071: {
    ref: '10671',
    name: 'MYCODE Resurfacing Retinol Renewing Facial Serum',
    line: 'MYCODE ADVANCED',
    category: 'serum',
    step: 'Serum',
    phase: 'active',
    professional: false,
    homecare: true,
    goals: ['anti_age', 'renewal', 'retinol', 'pigmentation', 'firming'],
    concerns: ['wrinkles', 'photoaging', 'uneven_texture', 'pigmentation'],
    skinTypes: ['mature', 'normal', 'oily', 'combination'],
    purpose: 'Erneuerndes Retinol-Serum bei Photoaging, Falten, ungleichmäßiger Textur und Hauterneuerung.',
  },

  mycode_072: {
    ref: '10672',
    name: 'MYCODE Resurfacing Retinol Repairing Face Cream',
    line: 'MYCODE ADVANCED',
    category: 'cream',
    step: 'Pflege',
    phase: 'final',
    professional: false,
    homecare: true,
    goals: ['anti_age', 'renewal', 'repair', 'retinol_support'],
    concerns: ['wrinkles', 'photoaging', 'uneven_texture', 'pores'],
    skinTypes: ['mature', 'normal', 'oily', 'combination'],
    purpose: 'Reparierende Retinol-Pflege zur Unterstützung der Hauterneuerung und Regeneration.',
  },

  mycode_095: {
    ref: '10696',
    name: 'MYCODE Hydronutrition Hydro-Nourishing Face Mask',
    line: 'MYCODE ADVANCED',
    category: 'mask',
    step: 'Maske',
    phase: 'mask',
    professional: false,
    homecare: true,
    goals: ['hydration', 'nutrition', 'barrier_repair', 'regeneration'],
    concerns: ['dryness', 'dehydration', 'sensitivity', 'tightness'],
    skinTypes: ['dry', 'sensitive', 'mature'],
    purpose: 'Hydro-nährende Maske zur Unterstützung von Feuchtigkeit, Komfort und Regeneration.',
  },

  // =========================
  // SUMMESUN
  // =========================

  summsun_spf50_sensitive: {
    ref: '25001',
    name: 'SUMMESUN SPF50+ Sensitive Skin',
    line: 'SUMMESUN',
    category: 'spf',
    step: 'Schutz',
    phase: 'protection',
    professional: false,
    homecare: true,
    goals: ['sun_protection', 'sensitive', 'anti_photoaging', 'hydration'],
    concerns: ['redness', 'photoaging', 'sensitivity'],
    skinTypes: ['sensitive', 'all'],
    purpose: 'Täglicher UVA/UVB-Schutz für empfindliche Haut.',
  },

  summsun_spf50_cc: {
    ref: '25002',
    name: 'SUMMESUN SPF50+ CC Cream',
    line: 'SUMMESUN',
    category: 'spf',
    step: 'Schutz',
    phase: 'protection',
    professional: false,
    homecare: true,
    goals: ['sun_protection', 'even_tone', 'anti_photoaging'],
    concerns: ['uneven_tone', 'pigmentation', 'photoaging'],
    skinTypes: ['all'],
    purpose: 'Täglicher SPF50+ mit pigmentierten Mikrosphären für einen ebenmäßigeren Teint.',
  },
}
